# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.34.0"

package:
  name: selenium-manager
  version: ${{ version }}

source:
  url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-${{ version }}.tar.gz
  sha256: 3939922d10d7058d7c2298b600b285c0ed1116c3fc71e7d127582017954ac727

build:
  number: 0
  script:
    file: build-selenium-manager

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses

tests:
  - script:
      - selenium-manager --version
      - selenium-manager --help
      - ls "${SE_MANAGER_PATH}" || dir "%SE_MANAGER_PATH%"

about:
  homepage: https://github.com/SeleniumHQ/selenium
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - NOTICE
  summary: |-
    Selenium Manager is a standalone tool that automatically manages the browser
    infrastructure required by Selenium (i.e., browsers and drivers).

extra:
  recipe-maintainers:
    - conda-forge/selenium
    - bollwyvl
