# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.49.0"
  prefix_env_var: ${{ "${PREFIX}" if unix else "%PREFIX%" }}

package:
  name: selenium-manager
  version: ${{ version }}

source:
  url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-${{ version }}.tar.gz
  sha256: 67ff5dd5f1f5b6d6e6965b383ecc9ee9a112e5a255b81bde9deefc2f20ba3cf5

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      - if: osx
        then:
          - export RUSTFLAGS="-C link-args=-Wl,-rpath,${PREFIX}/lib"
      - if: linux
        then:
          - export RUSTFLAGS="-C link-arg=-Wl,-rpath-link,${PREFIX}/lib -L${PREFIX}/lib"
      - cd rust
      - cargo auditable install --locked --no-track --root=${{ prefix_env_var }} --path=.
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      - cd "${{ RECIPE_DIR }}"
      - python build-selenium-manager-env-json.py

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses
    - python *

tests:
  - package_contents:
      strict: true
      bin:
        - if: unix
          then: selenium-manager
      files:
        - etc/conda/env_vars.d/selenium-manager.json
        - if: win
          then:
            - Scripts/selenium-manager.exe
  - script:
      - selenium-manager --version
      - selenium-manager --help
      - ls "${SE_MANAGER_PATH}" || dir "%SE_MANAGER_PATH%"

about:
  homepage: https://github.com/SeleniumHQ/selenium
  license: Apache-2.0
  license_file:
    - rust/THIRDPARTY.yml
    - LICENSE
    - NOTICE
  summary: |-
    Selenium Manager is a standalone tool that automatically manages the browser
    infrastructure required by Selenium (i.e., browsers and drivers).

extra:
  recipe-maintainers:
    - conda-forge/selenium
    - bollwyvl
